// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTiT5C_9oot55vGPra-ufGFPCi1D9DzA',
    appId: '1:877004859281:web:6e45966afe32b740431c30',
    messagingSenderId: '877004859281',
    projectId: 'fir-daa3d',
    authDomain: 'fir-daa3d.firebaseapp.com',
    storageBucket: 'fir-daa3d.appspot.com',
    measurementId: 'G-26TRXPTMTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZF-ojeU7tuxyLjMZitZMAmVKqj4lgxv8',
    appId: '1:877004859281:android:65f83cd8253c7352431c30',
    messagingSenderId: '877004859281',
    projectId: 'fir-daa3d',
    storageBucket: 'fir-daa3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoQhtbPCGHm2KEvFuKoqpJFldB_wGThvM',
    appId: '1:877004859281:ios:148689f2a44eb00b431c30',
    messagingSenderId: '877004859281',
    projectId: 'fir-daa3d',
    storageBucket: 'fir-daa3d.appspot.com',
    iosBundleId: 'com.example.todoTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoQhtbPCGHm2KEvFuKoqpJFldB_wGThvM',
    appId: '1:877004859281:ios:148689f2a44eb00b431c30',
    messagingSenderId: '877004859281',
    projectId: 'fir-daa3d',
    storageBucket: 'fir-daa3d.appspot.com',
    iosBundleId: 'com.example.todoTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxTiT5C_9oot55vGPra-ufGFPCi1D9DzA',
    appId: '1:877004859281:web:f3805c11b21f8c9a431c30',
    messagingSenderId: '877004859281',
    projectId: 'fir-daa3d',
    authDomain: 'fir-daa3d.firebaseapp.com',
    storageBucket: 'fir-daa3d.appspot.com',
    measurementId: 'G-WGJC74QYM0',
  );
}
